stepSize: 5
keyboardMode: false
dontReplaceSV: false
upscroll: false
colorThemeIndex: 9
styleThemeIndex: 1
effectFPS: 90
cursorTrailIndex: 1
cursorTrailShapeIndex: 1
cursorTrailPoints: 20
cursorTrailSize: 5
snakeSpringConstant: 1
cursorTrailGhost: false
rgbPeriod: 5
drawCapybara: true
drawCapybara2: false
drawCapybara312: false
selectTypeIndex: 5
placeTypeIndex: 1
editToolIndex: 5
showExportImportMenu: false
importData: ''
exportCustomSVData: ''
exportData: ''
debugText: debug
scrollGroupIndex: 1
BETA_IGNORE_NOTES_OUTSIDE_TG: true
advancedMode: false
