stepSize: 5
keyboardMode: false
dontReplaceSV: false
upscroll: false
colorThemeIndex: 9
styleThemeIndex: 1
effectFPS: 90
cursorTrailIndex: 1
cursorTrailShapeIndex: 1
cursorTrailPoints: 10
cursorTrailSize: 5
snakeSpringConstant: 1
cursorTrailGhost: false
rgbPeriod: 2
drawCapybara: false
drawCapybara2: false
drawCapybara312: false
selectTypeIndex: 1
placeTypeIndex: 1
editToolIndex: 1
showExportImportMenu: false
importData: ''
exportCustomSVData: ''
exportData: ''
debugText: debug
scrollGroupIndex: 1
BETA_IGNORE_NOTES_OUTSIDE_TG: false
advancedMode: false
